# Generated by Django 4.2 on 2023-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField()),
                ('comment_author', models.CharField(max_length=25)),
                ('comment_content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField()),
                ('post_author', models.CharField(max_length=25)),
                ('post_title', models.CharField(max_length=40)),
                ('post_content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_pass', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
